---
description: Pipeline for parsing TYCHON STIG Results
processors:  
  - dot_expander:
      field: "*"
  - set:
      if: "!(ctx.containsKey('id')) && ctx.tychon.containsKey('id') && ctx.rule.containsKey('id')"
      field: id
      value: '{{tychon.id}}_{{rule.id}}'  
  - set:      
      field: _id
      value: '{{id}}'     
  - set:
      field: '@timestamp'
      value: '{{_ingest.timestamp}}'
  - set:
      if: "ctx.containsKey('rule') && ctx.rule.containsKey('test_result')"
      field: rule.result
      value: '{{rule.test_result}}'
  - remove:
      if: "ctx.containsKey('rule') && ctx.rule.containsKey('test_result')"      
      field: rule.test_result
  - set:
      field: ecs.version
      value: '8.8.0'
  - set:
      field: event.kind
      value: state
  - set:
      field: event.module
      value: tychon
  - set:
      field: event.category
      value: [host]
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - convert:
      field: host.uptime
      type: long
  - script:
      source: ctx.host.mac = ctx.host.mac.replace(':','-')
  - convert:
      field: host.uptime
      type: long
  - gsub:
      field: host.mac
      pattern: ":"
      replacement: "-"
  - convert:
      field: script.current_duration
      type: float
  - convert:
      field: rule.weight
      type: float
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: '{{{ _ingest.on_failure_message }}}'
